import cors from "cors";
import express, { Router } from "express";
import cookieParser from "cookie-parser";
import { authRouter } from "./routes/auth.routes.js";
import { songRouter } from "./routes/song.routes.js";
const app = express();
app.use(cors({ origin: "http://localhost:5173", credentials: true }));
app.use(express.json());
app.use(cookieParser());
app.use("/api", authRouter);
app.use("/api", songRouter);
export default app;
